### ISSUE TITLE
Spree Ruby Gem (Security Fix for all Spree Versions)

### ISSUE THREAD

**Issue by skorth** [rubysec/ruby-advisory-db#132]
"A vulnerability in the API was discovered which could allow an attacker to commit CSRF gaining access to private information." https://spreecommerce.com/blog/security-updates-2015-3-3

I didn't found any official identifier.

**Comment by phillmv** [comment]
Hrm. @postmodern what are your feels re: waiting for an osvdb or cve? If Egor reported it, surely that'll follow.

**Comment by postmodern** [comment]
Yes, OSVDB at the bare minimum. I'm surprised OSVDB hasn't already created a report for it.

**Comment by postmodern** [comment]
Finally! http://osvdb.org/show/osvdb/119205
