### ISSUE TITLE
Update rubysec.github.io on every commit

### ISSUE THREAD

**Issue by reedloden** [rubysec/ruby-advisory-db#160]
Should use Travis CI / Circle CI to automagically update the `rubysec.github.io` repository and push changes live as new advisories are added to the `ruby-advisory-db` repository.

Right now, http://rubysec.com is woefully out of date. :(

Happy to help here if I can...

**Comment by dwradcliffe** [comment]
That is an excellent idea.

**Comment by skorth** [comment]
+1

**Comment by reedloden** [comment]
Anything I can do to help with this, or do one of you have time to do this?

**Comment by tarcieri** [comment]
:+1: :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:

**Comment by phillmv** [comment]
Tell me what I gotta do to enable it :D

**Comment by postmodern** [comment]
How would we connect one repository to the other without leaking access? Perhaps we could move the github pages for the advisories directly into `ruby-advisory-db` and render the pages there?

**Comment by phillmv** [comment]
>How would we connect one repository to the other without leaking access?

My understanding is most CI services let you perform some action on successful test passing; whether it can run a rake task and then push a commit idk.

Moving the gh pages to this repo is one possible solution.

**Comment by reedloden** [comment]
You'll have to give the CI service some form of access to either this repository or both repositories (the latter seems cleaner). You can either use one of your actual accounts or create a separate GitHub account with read/write permissions to those repositories that the CI service will get an OAuth token for.

**Comment by jeremyolliver** [comment]
You can have secure content such as api keys or deploy keys, even in a public repo http://docs.travis-ci.com/user/encryption-keys/

**Comment by reedloden** [comment]
Oh, I forgot GitHub added deploy keys. That would work just fine.

**Comment by reedloden** [comment]
From a few Google searches:

http://awestruct.org/auto-deploy-to-github-pages/
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
https://evansosenko.com/posts/automatic-publishing-github-pages-travis-ci/
https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db

Would have to modify the stuff a bit to deal with the second repository, but pretty simple overall.

**Comment by phillmv** [comment]
Kind of tight on bandwidth atm, if you give it to me as a series of numbered steps I'll set it up :+1:

**Comment by reedloden** [comment]
@phillmv --- here you go!

Been a bit busy with $JOB and $LIFE, so sorry for the delay.

Looks like CircleCI is currently used for testing commits / PRs to ruby-advisory-db, but since CircleCI doesn't support some of the features we'll use below, can't use it... As such, once everything is working, you'll likely want to just remove the CircleCI integration completely, as Travis CI will be handling things.

1. Sign up for Travis CI and grant it *limited* access to your GitHub account (read access to public repos + hook config). This is the default thing, so shouldn't have to do anything special, I believe. See http://docs.travis-ci.com/user/github-oauth-scopes/ for what permissions it asks for.
2. Go to the Travis CI profile for rubysec (https://travis-ci.org/profile/rubysec) and enable it for the ruby-advisory-db repository (make sure "Build pushes" and "Build pull requests" are both on).
3. Install the `travis` gem locally.
4. Generate a GitHub Personal Access Token (https://github.com/settings/tokens) with the `public_repo` scope. Save the token for the next step.
5. From within the `rubysec/ruby-advisory-db` checkout, run `travis encrypt 'GH_TOKEN=token'` where token is the token you received from GitHub.
6. Checkout #167 and modify the `secure` field in `.travis.yml` with output from previous command.
7. Push corrected version of #167 and cross your fingers.
8. http://rubysec.com should be updated with latest advisories!

**Comment by reedloden** [comment]
@phillmv, not sure what parts of the above you've done, but looks like you still need to generate a GitHub Personal Access Token, encrypt it using `travis encrypt 'GH_TOKEN=token'`, and update the `secure` field in .travis.yml with the encrypted output. This won't work until then.

**Comment by phillmv** [comment]
Derp. Okay. Will put that in shortly.
