### ISSUE TITLE
Support tracking vulnerabilities in rubygems itself

### ISSUE THREAD

**Issue by reedloden** [rubysec/ruby-advisory-db#165]
Similar to #20, would be great if vulnerabilities in `rubygems` could be tracked as part of this project. Right now, there isn't a good way to track that, and stuff gets missed. People rarely remember to upgrade `rubygems`.

**Comment by reedloden** [comment]
How about a top-level directory named 'rubygems'? We could overload `engine` for this, potentially... Thoughts?

**Comment by mveytsman** [comment]
Not sure if we need to overload `engine`, since all the advisories in the rubygems directory affect rubygems.

I'm for it.

**Comment by reedloden** [comment]
I think the goal is that every .yml file can live on its own, separate from the directory structure. That way, you don't need to parse the directory name in order to understand all the information in the advisory.

I'll put together a PR with all the rubygems issues.

**Comment by reedloden** [comment]
I decided to go with a new `libraries` top-level directory with `rubygems` inside it. That way, we could potentially track `stdlib` and `psych` issues in it as well (perhaps?).
