### ISSUE TITLE
Dealing with gem renames

### ISSUE THREAD

**Issue by reedloden** [rubysec/ruby-advisory-db#170]
https://rubygems.org/gems/bcrypt and https://rubygems.org/gems/bcrypt-ruby are the same gem (renamed in https://github.com/codahale/bcrypt-ruby/commit/aadbef48c12ae1bd4cb989c4373da2bda110f058), but we only track vulnerabilities for the latter. Should we just duplicate the directories somehow, or what's the best way to deal with this issue?

**Comment by reedloden** [comment]
Found another one... https://rubygems.org/gems/fog-dragonfly was renamed to https://rubygems.org/gems/dragonfly

**Comment by postmodern** [comment]
When a gem is renamed, but the older versions are not re-pushed to rubygems, we should just make a new `gem/$name` directory. If the gem rename was 1:1, then maybe we should consider setting up a symlink or copying the directory?

**Comment by reedloden** [comment]
Sadly, both bcrypt and dragonfly have overlapping gem versions, so I'll copy the ones over that make sense then. Can't really do a symlink, as the .yml file contains the gem name.

**Comment by phillmv** [comment]
I'm fine with making copies where appropriate; programmatically we can sort it out by cve/osvdb.

**Comment by reedloden** [comment]
Cool. Waiting for my latest PRs to get merged, and then I'll sort this out.

**Comment by mveytsman** [comment]
Looks like the discussion is resolved, closing.
