### ISSUE TITLE
Add advisory for handlebars-source <4.0.0 for "Quoteless attributes in templates can lead to XSS"

### ISSUE THREAD

**Issue by reedloden** [rubysec/ruby-advisory-db#216]
I just noticed that rubygems tracks handlebars.js via https://rubygems.org/gems/handlebars-source as well, sigh...

https://blog.srcclr.com/handlebars_vulnerability_research_findings/

https://srcclr.com/catalog/vulnerabilities/1878

https://github.com/wycats/handlebars.js/pull/1083

https://github.com/RetireJS/retire.js/commit/8d3c91e54f075a62cfc1f99edc792d811c35e3b3

**Comment by reedloden** [comment]
@VanessaHenderson How can I get you folks to let RubySec and Node Security Project know about these things when you find them? :)

**Comment by reedloden** [comment]
This issue also affects mustache.js (see https://github.com/janl/mustache.js/commit/378bcca8a5cfe4058f294a3dbb78e8755e8e0da5), which means https://github.com/knapo/mustache-js-rails is affected.

**Comment by reedloden** [comment]
Requested a CVE from MITRE, as well as an ID from OSVDB.

**Comment by phillmv** [comment]
Whoa, nice going @VanessaHenderson!

**Comment by reedloden** [comment]
`mustache-js-rails` v2.0.3 was just released with a [fix](https://github.com/knapo/mustache-js-rails/commit/0c79aec192b9b4a8491cdc3398bf6e4db535432b) for this issue.
