### ISSUE TITLE
Advisory template

### ISSUE THREAD

**Issue by JuanitoFatas** [rubysec/ruby-advisory-db#239]
Should we add advisory templates in Wiki, or other repository or this repository?

So we'll have same format of advisory and other people can help add advisories.

**Comment by jasnow** [comment]
Is the example template listed here enough?
  * https://github.com/rubysec/ruby-advisory-db/blob/master/CONTRIBUTING.md

**Comment by postmodern** [comment]
Closing this as we eventually disabled the Wiki and `README`/`CONTRIBUTING` is more visible.
