### ISSUE TITLE
add .gemspec and publish to rubygems

### ISSUE THREAD

**Issue by maliqq** [rubysec/ruby-advisory-db#296]
Make it possible to include this database in Gemfiles or gemspecs of other gems/apps, and retrieve database using `spec.full_gem_path`

**Comment by postmodern** [comment]
I'm more planning on extracting the code which downloads the database from [bundler-audit](https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/database.rb) into a separate gem.
