### ISSUE TITLE
Multiple vulnerabilities in RubyGems

### ISSUE THREAD

**Issue by thbar** [rubysec/ruby-advisory-db#299]
What do you think of adding the [vulnerabilities of RubyGems](https://www.ruby-lang.org/en/news/2017/08/29/multiple-vulnerabilities-in-rubygems/) itself to ruby-advisory-db?

It would make sure anyone using `bundler-audit` would get an error, for instance, and would encourage quick upgrading.

**Comment by zeckalpha** [comment]
It looks like @sho-h opened #298 for this.

**Comment by thbar** [comment]
Indeed! I missed that one. Closing the issue in favor of the PR. Thanks!
