### ISSUE TITLE
Add recent Nokogiri vulnerabilities 

### ISSUE THREAD

**Issue by dentarg** [rubysec/ruby-advisory-db#303]
Several vulnerabilities in libxml2 were reported: https://usn.ubuntu.com/usn/usn-3424-1/

They have all been addressed in Nokogiri 1.8.1 by updating libxml to 2.9.5.

See https://github.com/sparklemotion/nokogiri/issues/1673 for more information.

**Comment by phillmv** [comment]
Thank you both!
