### ISSUE TITLE
Add Nokogiri XXE vulnerability

### ISSUE THREAD

**Issue by brynary** [rubysec/ruby-advisory-db#31]
https://github.com/sparklemotion/nokogiri/issues/693

Network vulnerability fixed in Nokogiri v1.5.4:

http://www.ruby-forum.com/topic/4402659

Not sure when local filesystem vulnerability was fixed.

**Comment by reedloden** [comment]
https://github.com/rubysec/ruby-advisory-db/blob/master/gems/nokogiri/OSVDB-90946.yml was added a while ago. Does that address this? I know it's really two separate issues, but I only see the one CVE / OSVDB assignment.

**Comment by mveytsman** [comment]
I believe 90946 covers this
