### ISSUE TITLE
Expired certificate on https://rubysec.com/

### ISSUE THREAD

**Issue by rafbm** [rubysec/ruby-advisory-db#376]
Not a great first impression for a security-focused project. Maybe this website is no longer relevant, but it’s linked in the GitHub repo header:

<img width="505" alt="screen shot 2019-02-17 at 08 09 30" src="https://user-images.githubusercontent.com/166943/52913373-8a153780-328b-11e9-8777-bf5cd14ec586.png">

<img width="863" alt="screen shot 2019-02-17 at 08 12 19" src="https://user-images.githubusercontent.com/166943/52913392-c5b00180-328b-11e9-97fd-60a8308c553a.png">

**Comment by phillmv** [comment]
duplicate of https://github.com/rubysec/rubysec.com/issues/10
