### ISSUE TITLE
[GHSA sync] Pull CVSS score from NVD

### ISSUE THREAD

**Issue by reedloden** [rubysec/ruby-advisory-db#399]
Can we pull the CVSS score(s) from NVD via https://github.com/olbat/nvdcve when writing advisories?

**Comment by reedloden** [comment]
@rschultheis ^^

**Comment by postmodern** [comment]
btw, I have plans to write an NVD library that we can use.

**Comment by phillmv** [comment]
fun fact: we're actually in the process of backloading cvss and cwes into the gh data. maybe another month or so should be able to sync it off the github feed 🤔

**Comment by jasnow** [comment]
Is this done?

**Comment by postmodern** [comment]
Closing this as the `github_advisory_sync` script now populates CVSS scores.
