### ISSUE TITLE
Include warnings for EOL ruby and gems 

### ISSUE THREAD

**Issue by cyc115** [rubysec/ruby-advisory-db#416]
End of life Ruby and Gems could be something `ruby-advisory-db` tracks. Tools like `bundler-audit` could then use this information to alert users fail builds. Any thoughts?

**Comment by reedloden** [comment]
I like the idea. Thoughts on how we might show this to folks? Or the schema format?

**Comment by BookOfGreg** [comment]
I like the idea, though can I ask it be the default but disable-able behind a flag. Since this forms part of CI for a lot of places this could end up blocking a lot of builds. Thoughts go out to a team I know contractually obligated to stay on ruby 1.8.x.

**Comment by cyc115** [comment]
> I like the idea, though can I ask it be the default but disable-able behind a flag. Since this forms part of CI for a lot of places this could end up blocking a lot of builds. Thoughts go out to a team I know contractually obligated to stay on ruby 1.8.x.

Good idea, do you guys prefer to have it switch on with a flag (vs. on by default and switch off with flag)? Like you said, having it on by default could end up blocking a lot of builds.

**Comment by postmodern** [comment]
End-of-Lifed rubies could be stored in [ruby-versions](https://github.com/postmodern/ruby-versions). End-of-Lifing isn't really a Security Advisory, so I don't think it really fits here. Although, Advisories for vulnerabilities in EOLed Rubies definitely can be added to ruby-advisory-db.

**Comment by postmodern** [comment]
Closing this as the scope of [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db) is security advisories for vulnerabilities.

**Comment by jasnow** [comment]
Might be of interest: https://github.com/marketplace/actions/xeol-end-of-life-eol-scan
