### ISSUE TITLE
Update titles/descriptions for NVD advisories.

### ISSUE THREAD

**Issue by FionaDL** [rubysec/ruby-advisory-db#441]
As suggested by @postmodern in comment https://github.com/rubysec/ruby-advisory-db/issues/251#issuecomment-606172546
it would be nice to update the titles/descriptions for each advisory on using NVD as a url. However, one thing I noticed is that there are no titles on NVD site. The descriptions could be updated. What do you think is the best approach @postmodern ?

**Comment by postmodern** [comment]
Hmm let's wait on `titles` since that will require manually summarizing the description. Descriptions can be scraped from NVD (`//p[@data-testid="vuln-description"]`).

**Comment by FionaDL** [comment]
Hi @simar7 !  Yes, I think the idea was that since the titles are leftover from the old links to the OSVDB website that we should update the titles and descriptions to match the links that they are now pointing too. Unfortunately the https://nvd.nist.gov site doesn't seem to use titles. They do have updated descriptions though.

**Comment by simar7** [comment]
> Hi @simar7 ! Yes, I think the idea was that since the titles are leftover from the old links to the OSVDB website that we should update the titles and descriptions to match the links that they are now pointing at. Unfortunately the https://nvd.nist.gov site doesn't seem to use titles. They do have updated descriptions though.

Thanks. I've created a PR here to address it https://github.com/rubysec/ruby-advisory-db/pull/456

**Comment by postmodern** [comment]
Closing since #456 was merged.
