### ISSUE TITLE
ReversingLabs discovered 725 Typesquating Gems

### ISSUE THREAD

**Issue by tleish** [rubysec/ruby-advisory-db#444]
Original Article: [ReversingLabs: Mining for malicious Ruby gems](https://blog.reversinglabs.com/blog/mining-for-malicious-ruby-gems) (April 16, 2020)
> The RubyGems security team has been contacted, and all packages from reported users have been removed from the repository.

All affected packages: https://blog.reversinglabs.com/hubfs/Blog/ruby_malicious_gems.txt

Summarized Article: [Supply-chain attack hits RubyGems repository with 725 malicious packages](https://arstechnica.com/information-technology/2020/04/725-bitcoin-stealing-apps-snuck-into-ruby-repository/) (April 17, 2020)

Should these gems be added to the ruby-advisory db for those who already installed the gems even though they have been removed from RubyGems.org and there will never be a patched_version?  If yes, what happens if someone creates a safe gem with one of these names which has been removed, would it be removed from the db at that time?

**Comment by postmodern** [comment]
I would prefer that any TypoSquating or malicious gems be reported to [rubygems.org](https://rubygems.org/pages/security) immediately so they can yank them. As you've mentioned, there's issues with maintaining a list of malicious gems that have been yanked, but might still be floating around out there, but who's gem name might be later reclaimed later by a legitimate author. There's also the scenario where the TypoSquaters return and re-squate a previous yanked malicious gem. Not sure how to best handle that.
