### ISSUE TITLE
Recent Ruby CVEs are missing severity - is that intentional?

### ISSUE THREAD

**Issue by mensfeld** [rubysec/ruby-advisory-db#457]
Hey, I noticed that many of the recent Ruby related CVEs are missing severity. Is that intentional or can I fix this?

**Comment by reedloden** [comment]
@mensfeld Feel free to fix. What generally happens is that the CVE gets added prior to NVD or others assigning a CVSS score. I think a script that updates all the CVSS scores based on NVD would be nice.
