### ISSUE TITLE
Vulnerability with bundler 2.2.10

### ISSUE THREAD

**Issue by ghbren** [rubysec/ruby-advisory-db#461]
There is a vulnerability with bundler 2.2.10 that causes wrong gem versions to be installed. 
Please see https://github.com/rubygems/rubygems/issues/4383

Could you add it to the DB?  Thanks.

**Comment by reedloden** [comment]
I don't see where rubygems is treating that as a security issue. Can you follow the directions at https://rubygems.org/pages/security and report the issue to them? To add something to the ruby-advisory-db, we need an advisory ID such as CVE ID or GHSA ID.

**Comment by reedloden** [comment]
Closing due to lack of response.
