### ISSUE TITLE
The "use this form" link in the README is broken

### ISSUE THREAD

**Issue by dgollahon** [rubysec/ruby-advisory-db#474]
I was looking into how to submit to this database and noticed that the link in the README to a form to submit is broken. This may be a known issue, but I think the link should be fixed or removed or alternate instructions proved.

Thanks!

**Comment by phillmv** [comment]
Hey! The website's been in limbo because it's low-reward medium-effort, thank you for pointing out the link's broken. I went ahead and deleted the link for now.
