### ISSUE TITLE
commit febf9e8f404b4c8ad2860a33ca0f11e2c38e8c58 has a missing cve: field

### ISSUE THREAD

**Issue by JohnSmall** [rubysec/ruby-advisory-db#475]
commit febf9e8f404b4c8ad2860a33ca0f11e2c38e8c58 by @reedloden for the Nokogiri gem doesn't include a reference for cve: and therefore cannot be excluded in config/bundler-audit.ignore

This causes very big problems in our build pipeline because all Rails projects are failing security checks because we can't exclude the advisory.

**Comment by reedloden** [comment]
> commit febf9e8f404b4c8ad2860a33ca0f11e2c38e8c58 by @reedloden for the Nokogiri gem doesn't include a reference for cve: and therefore cannot be excluded in config/bundler-audit.ignore

Can you exclude based on the GHSA? If you're running a recent version of bundler-audit, you should be able to use the GHSA ID for ignores, unless there's some bug I am not currently aware of.

**Comment by reedloden** [comment]
So, specifically, try ignoring GHSA-7rrm-v45f-jp64. Let me know if that doesn't work for some reason.

**Comment by JohnSmall** [comment]
Updating bundler-audit worked, on my local machine. But I have to check it works in our Jenkins pipepline. So it looks OK, but don't close the ticket just yet.

**Comment by JohnSmall** [comment]
Yes it's working with the latest bundler-audit. Thanks
