### ISSUE TITLE
Place for ruby-advisory-db discussions

### ISSUE THREAD

**Issue by jasnow** [rubysec/ruby-advisory-db#541]
Can we have a place to have discussions on ruby-advisory-db related topics?

I do not see any Discord/Slack channels or GitHub Discussions link related to this project. 
Thanks.

**Comment by jasnow** [comment]
Discussion 1:
I ran this command and got zero (great): [Unreviewed Rubygem Advisories](https://github.com/advisories?query=type%3Aunreviewed+ecosystem%3Arubygems)

 1. How do I query for a string, such as "ruby" or "rails" or whatever, in the description field?
 2. How do I query for empty/nil values should as empty package or ecosystem fields?
 3. Any other tricks to find Ruby-related Advisories needing TLC?
 Thanks

**Comment by postmodern** [comment]
Note that the [GitHub Advisory Database](https://github.com/advisories) is separate from the ruby-advisory-db (which pulls from GitHub Advisory Database, and which bundler-audit uses). You can however `git grep` the ruby-advisory-db.

**Comment by jasnow** [comment]
I will use emails and GitHub issue for future discussions so I'm closing this issue.
