### ISSUE TITLE
OSVDB-96396

### ISSUE THREAD

**Issue by jmadkins** [rubysec/ruby-advisory-db#612]
After the [latest commit to master](https://github.com/rubysec/ruby-advisory-db/commit/84230706bb1f1886fab301d6768594edaf37800c) I'm now receiving the following error when running `bundler audit` but I'm unsure how to proceed. I looked at the referenced URLs and wasn't able to find anything regarding `OSVDB-96396`. This seems to be almost a 7+ year old issue.

```
Name: activemodel
Version: 7.0.5
Criticality: Unknown
URL: https://github.com/rails/rails/pull/8122
Title: Don't allow confirmation to pass if confirmation value is nil and doesn't match value.
Solution: remove or disable this gem until a patch is available!

Vulnerabilities found!
```

**Comment by krsyoung** [comment]
Not a surprise, but we're seeing the same thing regarding activemodel 7.0.4.3:

```
ruby-advisory-db:
  advisories:   753 advisories
  last updated: 2023-05-30 17:17:12 -0700
  commit:       84230706bb1f1886fab301d6768594edaf37800c
Name: activemodel
Version: 7.0.4.3
Criticality: Unknown
URL: https://github.com/rails/rails/pull/8122
Title: Don't allow confirmation to pass if confirmation value is nil and doesn't match value.
Solution: remove or disable this gem until a patch is available!
```

**Comment by krsyoung** [comment]
@postmodern ❤️ 

<img width="914" alt="image" src="https://github.com/rubysec/ruby-advisory-db/assets/5449541/a9e76b28-e958-4d70-9c7a-b9b2da0afd6e">

**Comment by postmodern** [comment]
Sorry should have caught that the advisory lacked a `patched_versions:` so it would flag everything.
