### ISSUE TITLE
[Pre537] Automate unaffected_versions conversion from GHSA to ruby-advisory-db

### ISSUE THREAD

**Issue by jasnow** [rubysec/ruby-advisory-db#649]
Automate unaffected_versions conversion from GHSA to ruby-advisory-db

**Comment by jasnow** [comment]
### patched_version and unaffecte_verions Use Cases for Testing:
 * https://gist.github.com/jasnow/7c99f4d9e8b838293ba407af373141af

### (Raw) unaffected_versions Use Cases for Testing:
 * https://gist.github.com/jasnow/c075a3ecbabed38640b93a171b5700bf

**Comment by jasnow** [comment]
Please review Roadmap above for missing unaffected_versions variables.

Is this true?
 * FYI: The only style rules regarding unaffected_versions field is be [double] quoted (CONTRIBUTING.md) and pass "rake" linting check.

**Comment by postmodern** [comment]
Closed by PR #676.
