### ISSUE TITLE
CircleCi Deploy Key Change causing download errors

### ISSUE THREAD

**Issue by cgrafton** [rubysec/ruby-advisory-db#827]
We're unable to clone this repo when using the deploy key that's set up in our CircleCI. The key is correctly set up in github as a deploy key. Here's the error message that git returns when trying to clone from within the CircleCI container:

```
Download ruby-advisory-db ...
Cloning into '/home/circleci/.local/share/ruby-advisory-db'...
ERROR: Permission to rubysec/ruby-advisory-db.git denied to deploy key
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
failed to download https://github.com/rubysec/ruby-advisory-db.git to "/home/circleci/.local/share/ruby-advisory-db"

Exited with code exit status 1
```
and worth noting, this is not the only affected repo. We started receiving this error at the same time and there is an [issue](https://github.com/nvm-sh/nvm/issues/3442) on their repo as well.

```
=> Downloading nvm from git to '/home/circleci/.nvm'
=> Cloning into '/home/circleci/.nvm'...
ERROR: Permission to nvm-sh/nvm.git denied to deploy key
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Failed to clone nvm repo. Please report this!

Exited with code exit status 2
```

**Comment by acookin** [comment]
I think this is just an issue across the board with public github repos, we are also seeing:

```
Cloning into 'bats-core'...
ERROR: Permission to bats-core/bats-core.git denied to deploy key
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

my guess is that either circleci made a change to inject the insteadOf directive into the gitconfig:
```
~$ cat ~/.gitconfig
[safe]
	directory = *
[url "ssh://git@github.com"]
	insteadOf = https://github.com
[gc]
	auto = 0
```
or github changed the ability for deploy keys to clone public repos.

**Comment by cgrafton** [comment]
I reported a circle issue and it seems to be resolved, closing.
